### ISSUE TITLE
Closes

### ISSUE THREAD

**Issue by kielec** [HoneyPots0/HPomb#2]
it keeps closing after I pick a number!

**Comment by HoneyPots0** [comment]
Can you please provide me ss or error code

**Comment by kielec** [comment]
it doesn't provide any error. It just closes

**Comment by HoneyPots0** [comment]
tell me what numeber you enter in first two input

thank you

**Comment by kielec** [comment]
all of them besides the exit doesnt work. It just crashes and closes it. I have mainly tried 01, 02, and 03. none of those work
